### ISSUE TITLE
ComboBox-multiple-selection setSelectedItems() bug 

### ISSUE THREAD

**Issue by L-G0WN** [DJ-Raven/raven-java-swing-tutorial-project#2]
I have a combomultiple connect with me bd and i want selected "English"
![image](https://github.com/DJ-Raven/raven-java-swing-tutorial-project/assets/147130445/debd7732-5259-4bcb-b315-87a1b6a5d8dd)

But if i want uncheck "English"
![image](https://github.com/DJ-Raven/raven-java-swing-tutorial-project/assets/147130445/eb5d9641-2348-48b3-8de5-828921bb6984)

item was not remove and if i select again appear a new item
![image](https://github.com/DJ-Raven/raven-java-swing-tutorial-project/assets/147130445/be896ecd-5090-440f-b293-637d7409b39f)

**Comment by DJ-Raven** [comment]
@L-G0WN I has try to test it. but no any issues like this. can you show full code ?

**Comment by L-G0WN** [comment]
JFrame 

    `public NewJFrame() {
        initComponents();

        loadSubjects();

        List<String> list = new ArrayList<>();
        list.add("Ingles");
        list.add("Sociología");
        comboBoxMultiSelection1.setSelectedItems(list);
    }`

Method set model

    `private void loadSubjects() {
        List<String> subjects = serviceManageTeachers.getSubjects();

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        for (String subject : subjects) {
            model.addElement(subject);
        }

        comboBoxMultiSelection1.setModel(model);
    }`

Method for get subjects

    `public static List<String> getSubjects() {
        List<String> subjects = new ArrayList<>();
        String selectSQL = "SELECT name FROM Subjects";

        try ( Connection conn = ConnectionTo.getConnection();  PreparedStatement pstmt = conn.prepareStatement(selectSQL);  ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                subjects.add(rs.getString("name"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return subjects;
    }`
